/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        String boldAnsi = "\033[1m";
        String resetAnsi = "\033[0m";
        String redAnsi = "\033[31m";

        String line = "----------------------------";
        String appTitle = "[팀 프로젝트 관리 시스템]";

        String[] menus = new String[]{
            "회원",
            "팀",
            "프로젝트",
            "게시판",
            "도움말",
            "종료"
        };

        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + appTitle + resetAnsi + "\n");

        for (int i = 0; i < menus.length; i++) {
            if ("종료".equals(menus[i])) {
//                System.out.printf("%s%d. %s%s\n", (boldAnsi + redAnsi), (i + 1), menus[i],
//                    resetAnsi);
                System.out.println(boldAnsi + redAnsi + (i + 1) + ". " + menus[i] + resetAnsi);
            } else {
                System.out.println((i + 1) + ". " + menus[i]);

            }

        }
//        System.out.println(menus[0]);
//        System.out.println(menus[1]);
//        System.out.println(menus[2]);
//        System.out.println(menus[3]);
//        System.out.println(menus[4]);
//        System.out.println(boldAnsi + redAnsi + menus[5] + resetAnsi);
        System.out.println(boldAnsi + line + resetAnsi);

        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.print("> ");
            try {
                int menuNum = scanner.nextInt();

                if (menuNum >= 1 && menuNum <= menus.length) { // 입력값이 1~6 범위일 때
                    if ("종료".equals(menus[menuNum - 1])) {
                        break;
                    }
                    System.out.println(menus[menuNum - 1]);

                } else {
                    System.out.println("메뉴 번호가 옳지 않습니다.");
                }

            } catch (InputMismatchException e) {
                System.out.println("유효한 입력이 아닙니다.");
                scanner.next();
            }

        }
        System.out.println("종료합니다");
        scanner.close();
    }
}
