/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String boldAnsi = "\033[1m";
        String resetAnsi = "\033[0m";
        String redAnsi = "\033[31m";

        String line = "----------------------------";
        String appTitle = "[팀 프로젝트 관리 시스템]";
        String menu1 = "1. 회원";
        String menu2 = "2. 팀";
        String menu3 = "3. 프로젝트";
        String menu4 = "4. 게시판";
        String menu5 = "5. 도움말";
        String menu6 = "6. 종료";


        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + appTitle + resetAnsi + "\n");
        System.out.println(menu1);
        System.out.println(menu2);
        System.out.println(menu3);
        System.out.println(menu4);
        System.out.println(menu5);
        System.out.println(boldAnsi + redAnsi + menu6 + resetAnsi);
        System.out.println(boldAnsi + line + resetAnsi);

        Scanner scanner = new Scanner(System.in);
        
        while (true){
            System.out.print("> ");
            if (scanner.hasNextInt()){
                int menuNum = scanner.nextInt();
                switch (menuNum){
                    case 1:
                        System.out.println(menu1.substring(3)); break;
                    case 2:
                        System.out.println(menu2.substring(3)); break;
                    case 3:
                        System.out.println(menu3.substring(3)); break;
                    case 4:
                        System.out.println(menu4.substring(3)); break;
                    case 5:
                        System.out.println(menu5.substring(3)); break;
                    case 6:
                        System.out.println("종료합니다.");
                        scanner.close();
                        return;
                    default:
                        System.out.println("메뉴 번호가 옳지 않습니다."); break;
                }
            }else {
                System.out.println("숫자만 입력해 주세요.");
                scanner.next();
            }
        }
    }
}
